[package]
name = "metricsrbx/election-system"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
Fusion = "elttob/fusion@0.3.0"
ProfileService = "madstudioroblox/profileservice@1.0.0"
Cmdr = "evaera/cmdr@1.11.0"
TestEZ = "roblox/testez@0.4.1"